import setuptools

setuptools.setup(name='optiml',
                 version='1.7',
                 author='Donato Meoli',
                 author_email='donato.meoli@outlook.com',
                 description='Optimizers for/and sklearn compatible Machine Learning models',
                 long_description=open('README.md').read(),
                 long_description_content_type='text/markdown',
                 license='MIT',
                 url='https://github.com/dmeoli/optiml',
                 packages=setuptools.find_packages(),
                 install_requires=['autograd',
                                   'casadi',
                                   'cvxopt',
                                   'cvxpy',
                                   'matplotlib',
                                   'numpy',
                                   'pytest',
                                   'qpsolvers',
                                   'quadprog',
                                   'scikit-learn',
                                   'scipy',
                                   'wurlitzer'],
                 python_requires='>=3.9')
